- hosts: logstash 
  become: yes 
  tasks:
    - name: Add an Apt signing key
      ansible.builtin.apt_key:
        url: https://packages.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Add EC Repo
      ansible.builtin.apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
        state: present

    - name: Install logstash and Java 
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - logstash 
          - default-jre
          - default-jdk
          - net-tools 

    - name: Create env JAVA_HOME 
      ansible.builtin.lineinfile:
        path: /etc/environment 
        line: JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"

    - name: Set CAP_NET_BIND_SERVICE+eip on java
      community.general.capabilities:
        path: /usr/share/logstash/jdk/bin/java
        capability: CAP_NET_BIND_SERVICE+eip
        state: present

    - name: Creating link to the java libraries
      ansible.builtin.file:
        src: /usr/share/logstash/jdk/lib/jli/libjli.so
        dest: /usr/lib/libjli.so
        state: link

    - name: Run ldconfig
      command: ldconfig

    - name: Restart logstash service 
      ansible.builtin.systemd:
        state: restarted
        enabled: yes
        name: logstash 

    - name: Check if a reboot is needed on all servers
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: Reboot the box if kernel updated
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
