- hosts: masters
  become: yes 
  tasks:
    #    - name: Add Java Repository
    #      ansible.builtin.apt_repository:
    #        repo: ppa:webupd8team/java

    #    - name: Install Java
    #      ansible.builtin.apt:
    #        name: oracle-java8-installer
    #       state: present
    #        update_cache: yes

    - name: Install Java 
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - default-jre
          - default-jdk

    - name: Create env JAVA_HOME 
      ansible.builtin.lineinfile:
        path: /etc/environment 
        line: JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"

    - name: Check if a reboot is needed on all servers
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: Reboot the box if kernel updated
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
